format_version: 5
pipelines:
  Docker_Enki:
    group: Enki
    display_order: 10
    label_template: ${code[:10]}
    materials:
      code:
        type: configrepo
        destination: code
    stages:
      - build:
          jobs:
            maven:
              elastic_profile_id: "maven.build-docker-image"
              tasks:
                - script: |
                    export CODE_PATH=$(pwd)/code
                    /scripts/update_version.sh
                - script: |
                    export CODE_PATH=$(pwd)/code
                    /scripts/build_maven.sh
              artifacts:
                - build:
                    source: code/target/
                    destination: target
      - publish:
          elastic_profile_id: "maven.build-docker-image"
          tasks:
            - fetch:
               stage: build
               job: maven
               source: target
               destination: code/
            - script: |
                export CODE_PATH=$(pwd)/code
                export SERVICE_NAME=enki
                cd $(pwd)/code/
                ls -al target/code/target
                cp target/code/target/enki-*-jar-with-dependencies.jar target/
                /scripts/build_docker.sh
      - scan:
          elastic_profile_id: "scan-project"
          tasks:
            - fetch:
               stage: build
               job: maven
               source: target
               destination: code/
            - script: |
                cd $(pwd)/code/
                ls -al target/code/target
                sonar-scanner -X
