format_version: 5
environments:
  Building:
    pipelines:
      - KafkaTopics
pipelines:
  KafkaTopics:
    group: Kafka-Databus
    label_template: ${code[:10]}
    materials:
      code:
        type: configrepo
        destination: code
      image:
        pipeline: VM_KafkaDatabus
        stage: terraform
    stages:
      - terraform:
          elastic_profile_id: "deploy-terraform"
          tasks:
            - script: |
                export CODE_PATH=$(pwd)/code
                sh /scripts/deploy-terraform
