name: Release

on: [push]

jobs:

  up_version:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout sources
      uses: actions/checkout@v1
     
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up Apache Maven
      uses: stCarolas/setup-maven@v1
      with:
        maven-version: 3.5.4

    - name: Calculate new version
      id: next_version
      uses: zwaldowski/semver-release-action@v1
      with:
        dry_run: true
        bump: patch
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set new version in enki-core and enki-server
      run: |
        for module in enki-*
        do
          cd $module
          mvn -q io.takari.polyglot:polyglot-translate-plugin:translate -Dinput=pom.yml -Doutput=pom.xml
          mvn -q versions:set -DnewVersion=${{ steps.next_version.outputs.version }} -f pom.xml
          mvn -q io.takari.polyglot:polyglot-translate-plugin:translate -Dinput=pom.xml -Doutput=pom.yml
          cd ..
        done

    - name: Set new version in providers and modules
      run: |
        for module in $(ls modules)
        do
          cd modules/$module
          mvn -q io.takari.polyglot:polyglot-translate-plugin:translate -Dinput=pom.yml -Doutput=pom.xml
          mvn -q versions:set -DnewVersion=${{ steps.next_version.outputs.version }} -f pom.xml
          mvn -q io.takari.polyglot:polyglot-translate-plugin:translate -Dinput=pom.xml -Doutput=pom.yml
          cd ../..
        done
        for provider in $(ls providers)
        do
          cd providers/$provider
          mvn -q io.takari.polyglot:polyglot-translate-plugin:translate -Dinput=pom.yml -Doutput=pom.xml
          mvn -q versions:set -DnewVersion=${{ steps.next_version.outputs.version }} -f pom.xml
          mvn -q io.takari.polyglot:polyglot-translate-plugin:translate -Dinput=pom.xml -Doutput=pom.yml
          cd ../..
        done

    - name: Push pom.yml with new version
      uses: github-actions-x/commit@v2.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'bump version'
        files: "./*"

    - name: Tag new version
      uses: zwaldowski/semver-release-action@v1
      with:
        bump: patch
        github_token: ${{ secrets.GITHUB_TOKEN }}

  build_core:
    needs: [up_version]
    runs-on: ubuntu-latest

    steps:

      - name: Checkout sources
        uses: actions/checkout@v1
        with:
          ref: master
     
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Apache Maven
        uses: stCarolas/setup-maven@v1
        with:
          maven-version: 3.5.4
  
      - name: Publish Enki Core
        run: mvn -B package deploy -Dgithub.token=${{ secrets.GITHUB_TOKEN }} -s ../.github/workflows/settings.xml
        working-directory: enki-core

      - name: Publish Enki Server
        run: mvn -B package deploy -Dgithub.token=${{ secrets.GITHUB_TOKEN }} -s ../.github/workflows/settings.xml
        working-directory: enki-server


  build_providers:
    needs: [build_core]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: [ "github", "one-repo", "bitbucket" ]

    steps:
    
      - name: Checkout sources
        uses: actions/checkout@v1
        with:
          ref: master
     
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Apache Maven
        uses: stCarolas/setup-maven@v1
        with:
          maven-version: 3.5.4

      - name: Publish Enki Module
        run: mvn -B package deploy -Dgithub.token=${{ secrets.GITHUB_TOKEN }} -s ../../.github/workflows/settings.xml
        working-directory: providers/${{ matrix.module }}

  build_modules:
    needs: [build_providers]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: [ "gocd-handlers" ]

    steps:
    
      - name: Checkout sources
        uses: actions/checkout@v1
        with:
          ref: master
     
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Apache Maven
        uses: stCarolas/setup-maven@v1
        with:
          maven-version: 3.5.4

      - name: Publish Enki Module
        run: mvn -B package deploy -Dgithub.token=${{ secrets.GITHUB_TOKEN }} -s ../../.github/workflows/settings.xml
        working-directory: modules/${{ matrix.module }}
